import {
    CommandInteraction,
    EmbedBuilder,
    SlashCommandBuilder
} from 'discord.js';
import fetch from 'node-fetch';

export const command = {
    data: new SlashCommandBuilder()
        .setName('inspire')
        .setDescription(
            'Returns an inspirational image generated by InspiroBot.'
        ),
    async execute(interaction: CommandInteraction) {
        const embed = new EmbedBuilder();
        const image = await fetch('https://inspirobot.me/api?generate=true');
        const data = await image.text();

        embed.setImage(`${data}`);

        await interaction.reply({
            embeds: [embed]
        });
    }
};
